### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by MateeSaafi** [MateeSaafi/2-Capstone#20]
https://github.com/matee-safi/2-Capstone/projects/1
- There are 2 people on our team.

**Comment by julie-ify** [comment]
Hi @matee-safi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should present the link to the project, not your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by rotimiazeez** [comment]
# Hi Team 👍🏽,
## Good job so far!
### To Highlight 👇🏽
- Good job implementing the required changes 👏🏽 
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR WORDS>

## Suggested changes
_Check the comments under the review._
### Kindly ensure all cards are assigned to team members. You should see a circle with the user's avatar on each card. See the example below:
<img width="372" alt="assigned_card" src="https://user-images.githubusercontent.com/44624138/226749648-0b0495bc-28fb-412e-8032-53d30b74d623.png">

### You have 2 people in this team so you should have just `Student A & B` in your card description 😉 

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag (@rotimiazeez) me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

**Comment by t-yanick** [comment]
# STATUS: CHANGES REQUIRED

Hi @matee-safi and @theresetuyi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

**- [ ] As indicated by the previous reviewer, all the cards should be assigned to team members. This is not currently the case. When I look at the cards that have not been assigned, they are for student C, but your team is made up of 2 members, meaning there should be no Student C. Kindly assigned all those cards between the two team members.**
Below are the links of unassigned cards:
- [[4pt] - Display Reservations pop up with selected item's details - Student C #13](https://github.com/matee-safi/2-Capstone/issues/13)
- [[3pt] - Display reservations for a given item on the Reservations pop-up - Student C #10](https://github.com/matee-safi/2-Capstone/issues/10)
- [[4pt] - Create feature: add new reservation - Student C #7](https://github.com/matee-safi/2-Capstone/issues/7)
- [[3pt] - Add reservations counter - Student C #4](https://github.com/matee-safi/2-Capstone/issues/4)
- [[3pt] - Add tests for reservations counter - Student C #1](https://github.com/matee-safi/2-Capstone/issues/1)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlphaNtihinduka** [comment]
# STATUS: APPROVED :green_circle: :clap: 
## Hello Team 🙋‍♂️🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:
